export const RAW_PREISPOLITIK_TSV = String.raw`
#separator:tab
#html:true
<b>An welcher Schnittstelle im Unternehmen befindet sich die Preispolitik?</b>	Die Preispolitik liegt an der <b>Schnittstelle von Marketing und Finanzen</b>, weshalb sie oft abteilungsübergreifend unterschiedlichen Zielsetzungen unterliegt.	Lektion 1
<b>Warum ist Preispolitik in der Praxis oft ineffektiv in Bezug auf die Zielsetzung?</b>	Viele Unternehmen verfolgen fehlerhaft <b>Absatz- oder Marktanteilsziele</b>, anstatt strategisch den Punkt zu suchen, bei dem sich der größtmögliche Gewinn realisieren lässt.	Lektion 1
<b>Warum sind Kennzahlen wie Umsatz oder Absatz keine verlässlichen Leitgrößen für die Preispolitik?</b>	Weder Umsatz, Absatz noch Marktanteil lassen einen verlässlichen Rückschluss auf die tatsächliche <b>Profitabilität</b> eines Unternehmens zu.	Lektion 1
<b>Welches abteilungsübergreifende Problem behindert oft ein effektives Preismanagement?</b>	Obwohl Marketing und Finanzen die Preispolitik als gemeinsame Schnittstelle haben, arbeiten beide Bereiche in der Praxis meist <b>unabhängig voneinander und ohne Angleichung</b> ihrer Ziele.	Lektion 1
<b>Wie sollte in der strategischen Preispolitik die Argumentation gegenüber dem Kunden aufgebaut sein?</b>	Es geht nicht primär darum, was der Kunde zu zahlen bereit ist, sondern darum zu erkennen, <b>welchen Wert das Produkt für den Kunden ausmacht</b>, und ihm diesen Wert rechtfertigend deutlich zu machen.	Lektion 1
<b>Warum gibt es oft eine Lücke zwischen theoretischen Pricing-Instrumenten und der tatsächlichen Unternehmenspraxis?</b>	Theoretische Konzepte (wie Preiselastizität) sind zwar bekannt, werden aber oft <b>aus Zeitnot oder hohem Aufwand</b> nicht eingesetzt, weshalb die Praxis oft auf ineffektivere Methoden zurückfällt.	Lektion 1
<b>Welche ineffektiven Methoden dominieren oftmals die Preissetzung in der Praxis?</b>	Anstelle von theoretisch fundierten Instrumenten wird die Praxis oftmals von <b>kostengesteuerter Preissetzung sowie erfahrungsbasierten Werten</b> determiniert.	Lektion 1
<b>Was versteht man im Preismanagement unter dem "Transaction-based View"?</b>	Der "Transaction-based View" beschreibt ein veraltetes Marketingverständnis, das primär <b>auf den reinen Verkauf und die einzelne Transaktion gerichtet</b> ist.	Lektion 1
<b>Was kennzeichnet den "Relation-based View" im Gegensatz zum "Transaction-based View"?</b>	Der "Relation-based View" zielt auf ein beziehungsorientiertes Verständnis ab, bei dem <b>langfristige Geschäftsbeziehungen gepflegt und Kundenwünsche einbezogen</b> werden.	Lektion 1
<b>Welche Hauptaufgabe hat die Preispolitik im modernen "Relation-based View"?</b>	Die zentrale Aufgabe ist es, den für den Kunden geschaffenen Wert <b>im Sinne des Unternehmens abzuschöpfen und zu monetarisieren</b>.	Lektion 1
<b>Wie wird der Begriff "Preismanagementprozess" definiert?</b>	Der Preismanagementprozess umfasst die <b>Gesamtheit aller Teilentscheidungen (z. B. Preispositionen) und Handlungen (z. B. Preiserhöhungen)</b>, die einen Einfluss auf den Transaktionspreis haben.	Lektion 1
<b>Warum sollte Preismanagement nicht bloß als einmalige "Preisoptimierung" betrachtet werden?</b>	Weil es ein <b>ganzheitlicher Prozess</b> ist, der über die reine Preisentscheidung hinausgeht und kontinuierlich den letztendlichen Transaktionspreis steuert.	Lektion 1
<b>Welche drei Kernfaktoren müssen beurteilt werden, um Preispolitik effektiv zu gestalten?</b>	Man muss valide einschätzen und verstehen, inwieweit <b>Kosten, Kunden und Wettbewerb</b> das preispolitische Umfeld eines Produktes prägen.	Lektion 1
<b>Welches Wissen über die unternehmensinternen Kosten ist für ein effektives Pricing unerlässlich?</b>	Das Management muss genau darüber informiert sein, in welcher Art und in welchem Umfang sich <b>Absatzänderungen auf die Kosten auswirken</b>.	Lektion 1
<b>Welches Wissen über das Kundenverhalten wird für eine erfolgreiche Preissetzung zwingend benötigt?</b>	Man muss verstehen, welche Rolle der Preis einer Ware für den Kunden <b>hinsichtlich seiner individuellen Kaufentscheidung</b> überhaupt spielt.	Lektion 1
<b>Wie muss eine effektive Preispolitik mit der Konkurrenz umgehen?</b>	Eine effektive Preispolitik zeichnet sich dadurch aus, dass sie das <b>künftige Verhalten und mögliche preisliche Reaktionen der Wettbewerber voraussieht</b>.	Lektion 1
<b>Welche strukturelle Veränderung erfordert eine strategische Preispolitik im Unternehmen?</b>	Sie erfordert ein Umdenken im zeitlichen Ablauf von Entscheidungen, begleitend dazu müssen <b>Entscheidungskompetenzen im Unternehmen verlagert</b> werden.	Lektion 1
<b>Zwischen welchen beiden Kernansprüchen muss das Preismanagement einen Ausgleich finden?</b>	Es muss dem Kundenanspruch auf wertige Ware entsprechen, aber gleichermaßen dem Unternehmensanspruch auf <b>Kostendeckung und Gewinnmaximierung</b> gerecht werden.	Lektion 1
<b>Welchen strategischen Anspruch sollte die Preispolitik in einem Unternehmen ganzheitlich haben?</b>	Preispolitik sollte den Anspruch haben, ein <b>wesentlicher Bestandteil der Unternehmensstrategie</b> zu sein, anstatt Renditen als rein willkürliches Nebenprodukt entstehen zu lassen.	Lektion 1
<b>Auf welchen drei Säulen basiert ein erfolgreiches Preismanagement zusammenfassend?</b>	Es basiert auf der Kenntnis von <b>Determinanten (wie Kosten, Wert)</b>, der Einschätzung von <b>Umfeldfaktoren (wie Zahlungsbereitschaft)</b> und der Beachtung von <b>Wechselwirkungen (wie Elastizitäten, Wettbewerbsreaktionen)</b>.	Lektion 1
<b>Was versteht man unter dem Preisspielraum?</b>	Der Preisspielraum ist die Spanne, in die der Preis fallen muss, um die Profitabilität des Unternehmens zu gewährleisten.	Lektion 2
<b>Welche beiden Faktoren definieren die Preisobergrenze für ein Produkt?</b>	Die Preisobergrenze wird im Wesentlichen durch den <b>Kundennutzen</b> und die <b>Wettbewerbspreise</b> definiert.	Lektion 2
<b>Was drückt die Preisbereitschaft aus?</b>	Die Preisbereitschaft gibt an, was der Kunde <b>maximal bereit ist</b>, für ein spezifisches Produkt zu zahlen.	Lektion 2
<b>Warum gelten Preisobergrenzen in der Praxis meist als Grenzzonen und nicht als harte Grenzen?</b>	Weil der Preis nicht immer das allein ausschlaggebende Kriterium für die Kaufentscheidung ist und Kunden oft bereit sind, für <b>bevorzugte Angebote höhere Preise</b> zu akzeptieren.	Lektion 2
<b>Durch welchen zentralen Faktor wird die Preisuntergrenze determiniert?</b>	Die Preisuntergrenze wird in der Regel durch die interne <b>Kostensituation</b> des Unternehmens bestimmt.	Lektion 2
<b>Was ist der wichtigste Aspekt bei der unternehmensinternen Kostenanalyse für die Preisfindung?</b>	Der wichtigste Aspekt ist die strikte <b>Trennung von fixen und variablen Kosten</b>.	Lektion 2
<b>Was charakterisiert fixe Kosten?</b>	Fixe Kosten bleiben <b>konstant</b> und fallen völlig <b>unabhängig von der tatsächlichen Ausbringungsmenge</b> (Produktionsmenge) an.	Lektion 2
<b>Was ist ein klassisches Beispiel für fixe Kosten?</b>	Die <b>Miete für ein Verwaltungsgebäude</b>.	Lektion 2
<b>Was zeichnet variable Kosten aus?</b>	Variable Kosten ändern sich <b>dynamisch in Abhängigkeit von der jeweils produzierten Ausbringungsmenge</b>.	Lektion 2
<b>Welchem Wert entspricht die absolute Preisuntergrenze im direkten Vertriebsgeschäft zumeist?</b>	Sie entspricht meist dem niedrigsten Preis in Höhe der <b>variablen Kosten</b>, zu dem ein Auftrag gerade noch angenommen wird.	Lektion 2
<b>Worin unterscheiden sich "zusätzliche Kosten" von "nicht zusätzlichen Kosten"?</b>	Nur <b>zusätzliche Kosten</b> steigen oder fallen generell infolge von Preisänderungen und dem damit verbundenen Mehr- oder Minderabsatz.	Lektion 2
<b>Was sind Zusatzkosten im Kontext der Preispolitik?</b>	Zusatzkosten sind jene Kosten, die sich bei einer Änderung der Preisgestaltung und des Absatzes wandeln und so die <b>relative Rentabilität</b> beeinflussen.	Lektion 2
<b>Welcher Kostenart entsprechen variable Kosten bei preispolitischen Entscheidungen?</b>	Variable Kosten sind bei der Preisgestaltung prinzipiell <b>immer Zusatzkosten</b>.	Lektion 2
<b>Sind Fixkosten bei Preisentscheidungen als Zusatzkosten zu werten?</b>	Nein, da Fixkosten vom Absatz des Produktes in der Regel <b>nicht betroffen</b> sind, werden sie bei Preisentscheidungen vereinfacht angenommen <b>nicht berücksichtigt</b>.	Lektion 2
<b>Welche Arten von Kosten sind relevant für die Preisbildung?</b>	Für die Preisbildung sind ausschließlich die <b>vermeidbaren Kosten (Zusatzkosten)</b> relevant.	Lektion 2
<b>Wie definiert man "vermeidbare Kosten"?</b>	Vermeidbare Kosten sind Kosten, die entweder <b>noch nicht entstanden</b> sind oder die durch Unternehmensentscheidungen <b>rückgängig gemacht</b> werden können.	Lektion 2
<b>In welchen Unternehmensbereichen lassen sich Kosten am ehesten vermeiden?</b>	Vermeidbare Kosten fallen oft im <b>Absatz (z. B. Werbeausgaben)</b> oder in der <b>Wiederbeschaffung (z. B. Einkauf, Produktion, Lagerhaltung)</b> an.	Lektion 2
<b>Was versteht man unter historischen Kosten?</b>	Historische Kosten sind in der Vergangenheit getätigte Aufwendungen, die das Unternehmen <b>nun in jedem Fall tragen muss</b>.	Lektion 2
<b>Wie lautet der englische Fachbegriff für historische, nicht mehr änderbare Kosten?</b>	<b>Sunk Costs</b>.	Lektion 2
<b>Sind Sunk Costs für die aktuelle Preisbildung relevant?</b>	Nein, Sunk Costs haben für die laufende Preissetzung <b>keine Relevanz</b>, da sie ohnehin unveränderlich sind.	Lektion 2
<b>Was ist ein typisches Beispiel für Sunk Costs?</b>	Historische und bereits getätigte Aufwendungen für <b>Forschung und Entwicklung</b>.	Lektion 2
<b>Welchen Zweck verfolgt die Deckungsbeitragsanalyse?</b>	Sie hilft dem Management, <b>Mindestpreise festzulegen</b> und pro Produkt zu ermitteln, in welchem Umfang Fixkosten abgetragen werden.	Lektion 2
<b>Was drückt der Deckungsbeitrag prinzipiell aus?</b>	Er stellt den Teil des Preises dar, der nach Abzug der variablen Kosten übrig bleibt, um den <b>Gewinn zu steigern</b> oder einen möglichen <b>Verlust zu mindern</b>.	Lektion 2
<b>Wie wird der Stückdeckungsbeitrag inhaltlich definiert?</b>	Der Stückdeckungsbeitrag ist die <b>Differenz aus dem Verkaufspreis und den variablen (bzw. vermeidbaren) Kosten</b> pro Stück.	Lektion 2
<b>Wie lautet die mathematische Formel für den Stückdeckungsbeitrag (DB)?</b>	$DB = \text{Verkaufspreis} - \text{variable Kosten}$	Lektion 2
<b>Wie lautet die englische Bezeichnung für den Deckungsbeitrag?</b>	<b>Contribution Margin (CM)</b>.	Lektion 2
<b>Wie lautet die Formel für den prozentualen Deckungsbeitrag (%DB) auf Grundlage des Gesamtabsatzes?</b>	$\%DB = \frac{\text{Gesamtdeckungsbeitrag}}{\text{Absatzerlös}} \cdot 100$	Lektion 2
<b>Wie lautet die Formel für den prozentualen Deckungsbeitrag bezogen auf ein einzelnes Stück?</b>	$\text{prozentualer DB} = \frac{DB}{\text{Preis}}$	Lektion 2
<b>Sollte ein Unternehmen aus strategischer Sicht negative Deckungsbeiträge akzeptieren?</b>	Nein, negative Deckungsbeiträge sind gemeinhin <b>zu vermeiden</b>, da hierbei die variablen Kosten den Umsatz übersteigen.	Lektion 2
<b>Was wird mit der Break-even-Analyse ermittelt?</b>	Sie ist eine <b>Wirtschaftlichkeitsanalyse</b>, die aufzeigt, bei welcher Kombination aus Absatzmenge, Stückpreis und Kosten ein Gewinn zu erwarten ist.	Lektion 2
<b>Welche drei betriebswirtschaftlichen Dimensionen betrachtet die Break-even-Analyse?</b>	<b>Absatz, Stückpreis und Kosten</b> (variabel und fix).	Lektion 2
<b>Was bedeutet Kostendeckung im Rahmen der Break-even-Analyse?</b>	Kostendeckung bedeutet, dass die Erlöse aus der Absatzmenge genau ausreichen, um <b>alle anfallenden Kosten zu decken</b>.	Lektion 2
<b>Wo exakt befindet sich der Break-even-Punkt im Diagramm?</b>	Er liegt genau dort, wo sich die <b>Umsatzlinie und die Gesamtkostenlinie überschneiden</b>.	Lektion 2
<b>Was gilt bezüglich des Unternehmensgewinns exakt am Break-even-Absatz?</b>	Bei dieser Ausbringungsmenge ist die Kostendeckung erreicht, der tatsächliche <b>Gewinn beträgt hier exakt Null</b>.	Lektion 2
<b>Was resultiert aus jedem abgesetzten Stück vor dem Erreichen des Break-even-Punktes?</b>	Jedes davor produzierte und abgesetzte Stück führt zu einem <b>operativen Verlust</b>.	Lektion 2
<b>Was resultiert aus jedem abgesetzten Stück nach dem Überschreiten des Break-even-Punktes?</b>	Jedes ab jetzt produzierte und abgesetzte Stück führt zu einem <b>direkten Gewinn</b> für das Unternehmen.	Lektion 2
<b>Wie lautet die Berechnungsformel für den Break-even-Absatz?</b>	$\text{Break-even-Absatz} = \frac{\text{Fixkosten}}{\text{Preis} - \text{variable Kosten}} = \frac{\text{Fixkosten}}{DB}$	Lektion 2
<b>Welchen Effekt hat eine generelle Senkung der Kostenstrukturen auf den Break-even-Punkt?</b>	Niedrigere Kosten <b>senken den Break-even-Punkt</b>, was es ermöglicht, Renditeziele früher oder mit niedrigeren Abgabepreisen zu erreichen.	Lektion 2
<b>Für welche operativen Produktentscheidungen eignet sich die Break-even-Analyse besonders?</b>	Sie ist besonders nützlich, wenn die <b>Einführung neuer oder die Elimination bestehender Produkte</b> entschieden werden muss.	Lektion 2
<b>Wie wird die Fixkostenlinie im Break-even-Diagramm dargestellt?</b>	Sie wird als durchgehende <b>horizontale Linie</b> gezeichnet, da sie sich nicht mit der Absatzmenge ändert.	Lektion 2
<b>An welchem Punkt startet die Gesamtkostenlinie im Break-even-Diagramm?</b>	Sie startet auf der Y-Achse exakt in Höhe der <b>Fixkosten</b>.	Lektion 2
<b>Wo beginnt die Umsatzlinie im Break-even-Diagramm und warum?</b>	Sie startet exakt im <b>Nullpunkt (Ursprung)</b>, da erst mit dem ersten abgesetzten Stück Umsatz (Erlös) generiert wird.	Lektion 2
<b>Wodurch wird die Steigung der Umsatzlinie bestimmt?</b>	Die Steigung der Umsatzlinie ergibt sich aus dem festgelegten <b>Verkaufspreis pro Stück</b>.	Lektion 2
<b>Warum steigt die Gesamtkostenlinie im Diagramm nach rechts oben an?</b>	Weil mit jeder produzierten Einheit die <b>variablen Kosten zu den Fixkosten</b> hinzukommen.	Lektion 2
<b>Welches Nebenziel verfolgt das Management bei der Break-even-Betrachtung bezüglich Kostenstrukturen?</b>	Das <b>Senken der fixen und/oder variablen Kosten</b>.	Lektion 2
<b>Weshalb sind reine Kostenbetrachtungen meist einfacher als Preis-Absatz-Funktionen?</b>	Da die notwendigen <b>Kosteninformationen unternehmensinterner Herkunft</b> sind und somit verlässlicher vorliegen.	Lektion 2
<b>Sind Kosten allein ausreichend für eine optimale Preisbestimmung?</b>	Nein, aber ein umfassendes Verständnis der Kostenseite ist zwingend nötig, um am Markt durchsetzbare <b>Verkaufspreise mit den eigenen Kosten abzugleichen</b>.	Lektion 2
<b>Inwiefern beeinflussen Wettbewerbspreise die Preisobergrenze?</b>	Sie bilden eine <b>externe Benchmark</b>, die Kunden zum Kauf bei der Konkurrenz bewegen kann und so die absatzbezogenen Preise des eigenen Unternehmens begrenzen.	Lektion 2
<b>Was versteht man allgemein unter dem "Wert" eines Produktes im Auge des Kunden?</b>	Der Wert ist die <b>Befriedigung</b>, die der Kunde durch den Kauf eines Produktes erzielt.	Lektion 3
<b>Wie werden die Begriffe "Nutzen" oder "Nutzwert" definiert?</b>	Als die Summe aller sachlichen und grundlegenden Funktionen (<b>Grundnutzen</b>) sowie der zusätzlichen Attribute (<b>Zusatznutzen</b>) eines Angebots.	Lektion 3
<b>Welche Rolle spielt der "Preis" für den Anbieter in Bezug auf den Produktnutzen?</b>	Der Preis dient dem Anbieter lediglich als <b>Austauschgröße</b>, um das betreffende Produkt gegen Geld zu tauschen.	Lektion 3
<b>Wie wird der Begriff "Konsumentenrente" definiert?</b>	Sie entsteht, wenn der individuelle Nutzen (also die Preisbereitschaft) des Käufers <b>höher liegt</b> als der vom Anbieter geforderte Preis.	Lektion 3
<b>Welche Auswirkung hat eine hohe Konsumentenrente auf einen Markt?</b>	Sie <b>lockt weitere Anbieter an</b>, da sie eine hohe Preisbereitschaft der Kunden und damit attraktive Gewinne verspricht.	Lektion 3
<b>Was drückt der "Tauschwert" (auch wirtschaftlicher Wert genannt) aus?</b>	Der Tauschwert ist der wirtschaftliche Wert unter Berücksichtigung von <b>Kaufalternativen (Konkurrenzangeboten)</b> und dem individuellen Nutzen des Käufers.	Lektion 3
<b>Was wird in der Preispolitik als "Referenzwert" bezeichnet?</b>	Der Referenzwert ist die preislich <b>billigste Alternative im Markt</b>, mit der sich jedes andere Angebot vergleichen lassen muss.	Lektion 3
<b>Was versteht man unter dem "Differenzierungswert"?</b>	Es ist der Wert, den die <b>Differenz zwischen dem eigenen Angebot und dem Referenzprodukt</b> für den Kunden besitzt.	Lektion 3
<b>Wie lautet die Herleitung zur Bestimmung des Differenzierungswertes?</b>	$\text{Differenzierungswert} = \text{Angebotspreis} - \text{Preis Referenzprodukt}$	Lektion 3
<b>Was drückt die "Preissensitivität" eines Kunden aus?</b>	Sie ist ein Indikator dafür, <b>wie stark der Preis in die individuelle Kaufentscheidung</b> des Kunden einfließt.	Lektion 3
<b>Was charakterisiert einen maximal preissensitiven Kunden?</b>	Er kauft <b>ausschließlich das Wettbewerbsprodukt</b>, selbst wenn dieses nur einen einzigen Cent billiger ist.	Lektion 3
<b>Was besagt der "Effekt bei wahrgenommenen Substituten" (Substituteneffekt)?</b>	Die Preissensitivität ist umso stärker, je höher der Preis des eigenen Produktes <b>im Vergleich zu wahrgenommenen Ersatzprodukten (Substitute)</b> ist. Beispiel: Milch im Kühlregal.	Lektion 3
<b>Was drückt der "Effekt des einzigartigen Wertes" aus?</b>	Die Preissensitivität des Kunden sinkt, je höher er die <b>einzigartigen Eigenschaften</b> (Alleinstellungsmerkmale) eines Produktes einstuft. Beispiel: Rolex-Armbanduhr.	Lektion 3
<b>Was versteht man unter dem "Wechselkosteneffekt"?</b>	Die Preissensitivität der Käufer ist geringer, je höher die <b>monetären und nicht monetären Kosten eines Wechsels</b> zu einem anderen Anbieter ausfallen. Beispiel: Wechsel des Stromanbieters.	Lektion 3
<b>Was beschreibt der "Effekt des schwierigen Vergleiches"?</b>	Die Preissensitivität sinkt, wenn Konsumenten die Alternativen und Wirkungen von Konkurrenzangeboten <b>nur schwer vergleichen können</b>. Beispiel: Medikamente.	Lektion 3
<b>Wie wirkt der "Preis-Qualitäts-Effekt"?</b>	Käufer sind deutlich weniger preissensitiv, wenn ein höherer Preis als <b>direkter Indikator für eine bessere Produktqualität</b> betrachtet wird. Beispiel: Whiskey für 80 EUR vs. 20 EUR.	Lektion 3
<b>Was besagt der "Ausgabeneffekt" in der Preispolitik?</b>	Käufer sind viel preissensitiver, wenn die Ausgaben für ein Produkt <b>im Verhältnis zum verfügbaren Einkommen</b> prozentual oder absolut sehr hoch ausfallen. Beispiel: Neuwagenkauf.	Lektion 3
<b>Was beschreibt der "Endnutzeneffekt"?</b>	Kunden reagieren <b>weniger preissensitiv auf Einzelbestandteile (Zubehör)</b>, wenn deren Preis im Verhältnis zum teuren Endnutzen (Hauptprodukt) steht. Beispiel: Extras beim Autokauf.	Lektion 3
<b>Was bewirkt der "Kostenteilungseffekt"?</b>	Die Preissensitivität sinkt, <b>je niedriger der vom Käufer selbst getragene finanzielle Anteil</b> am Gesamtkaufpreis ist. Beispiel: Arzt verschreibt Medikamente (Krankenkasse zahlt).	Lektion 3
<b>Was löst den "Fairness-Effekt" bei der Preissensitivität aus?</b>	Der Kunde reagiert stark preissensitiv, wenn der Produktpreis einen Rahmen überschreitet, der situativ <b>als "unfair" oder "unverhältnismäßig" gilt</b>. Fairness ist rein subjektiv.	Lektion 3
<b>Was beschreibt der "Lagerbestandseffekt"?</b>	Die Preissensitivität eines Kunden steigt an, wenn er prinzipiell in der Lage ist, ein Produkt <b>auf Vorrat zu kaufen und einzulagern</b>. Beispiel: Schokolade, Waschmittel.	Lektion 3
<b>Was drückt die "Preiselastizität der Nachfrage" prinzipiell aus?</b>	Sie gibt an, <b>wie sehr die Nachfrage nach einem Produkt auf eine Veränderung des Preises</b> reagiert.	Lektion 3
<b>Wie lautet die mathematische Formel zur Berechnung der Preiselastizität (E)?</b>	$E = \frac{\text{Stückabsatzänderung in \%}}{\text{Preisänderung in \%}}$	Lektion 3
<b>Warum besitzt die berechnete Preiselastizität in der Regel ein negatives Vorzeichen?</b>	Da Absatzänderungen und Preisänderungen normalerweise <b>in entgegengesetzte Richtungen</b> verlaufen (Preis steigt → Absatz sinkt).	Lektion 3
<b>Was bedeutet eine "elastische" Nachfrage?</b>	<b>Je höher der nominale Wert E</b> ist, desto elastischer (also stärker) reagiert die Nachfrageseite auf Preisänderungen.	Lektion 3
<b>Was bedeutet eine "unelastische" Nachfrage?</b>	<b>Je kleiner der nominale Wert E</b> ist, desto unelastischer (also schwächer) reagiert die Nachfrageseite auf Preisänderungen.	Lektion 3
<b>Was gibt die "Kreuzpreiselastizität" an?</b>	Sie gibt das Ausmaß der Wirkung des <b>Konkurrenzpreises (Produkt B)</b> auf den <b>eigenen Absatz (Produkt A)</b> an.	Lektion 3
<b>Wie lautet die Formel zur Berechnung der Kreuzpreiselastizität?</b>	$\text{Kreuzpreiselastizität} = \frac{\text{relative Mengenänderung Produkt A}}{\text{relative Preisänderung Produkt B}}$	Lektion 3
<b>Warum lassen sich Preiselastizitäten nur eingeschränkt für zukünftige Prognosen nutzen?</b>	Da sie auf <b>vergangenheitsbezogenen Betrachtungen</b> basieren und der Preis bei Kaufentscheidungen nicht das einzige Argument ist.	Lektion 3
<b>Was bedeutet der Interpretationswert einer Preiselastizität von E = -2?</b>	Die prozentuale Absatzänderung macht exakt <b>das Zweifache der prozentualen Preisänderung</b> aus (z.B. 10 % Preissenkung bewirken 20 % Absatzzuwachs).	Lektion 3
<b>Wodurch unterscheidet sich der Tauschwert vom reinen Nutzwert?</b>	Der Nutzwert fokussiert sich rein auf den Käufernutzen, während der Tauschwert <b>mögliche Kaufalternativen im Markt</b> ergänzend miteinbezieht.	Lektion 3
<b>Welche zwingende Bedingung muss erfüllt sein, damit der Effekt des einzigartigen Wertes wirkt?</b>	Der Kunde muss die Produktdifferenzierung <b>tatsächlich wahrnehmen, wichtig finden und ihr einen Wert beimessen</b>.	Lektion 3
<b>Was sind Beispiele für "nicht monetäre" Wechselkosten?</b>	Organisatorischer <b>Aufwand oder reine Bequemlichkeit</b>, beispielsweise bei einem Wechsel des Stromanbieters.	Lektion 3
<b>Welche Nachfrageform prägt den Endnutzeneffekt bei Zubehör?</b>	Das Zubehör unterliegt einer reinen <b>abgeleiteten Nachfrage</b>, die an den Kauf des Hauptprodukts gekoppelt ist.	Lektion 3
<b>Ist "Fairness" bei Preisen eine objektiv messbare Größe?</b>	Nein, Fairness ist in diesem Kontext eine <b>rein subjektiv wahrgenommene Größe</b> des jeweiligen Kunden.	Lektion 3
<b>Entspricht der wirtschaftliche Wert in der Realität exakt dem Höchstpreis, den Kunden zahlen würden?</b>	Nein, dies wäre nur bei <b>vollständigen Marktinformationen und vollkommen rationalen Entscheidungen</b> der Fall.	Lektion 3
<b>Wie kann der wirtschaftliche Wert in der Unternehmenspraxis empirisch ermittelt werden?</b>	Beispielsweise mittels <b>Befragung der Kunden</b>.	Lektion 3
<b>Was kennzeichnet einen Kunden mit niedriger Preissensitivität?</b>	Der Preis ist für seine Kaufentscheidung <b>von nachrangigem Gewicht</b>, da er z.B. einen besonderen Nutzen des Gutes erwartet.	Lektion 3
<b>Warum kann ein Anbieter den Nutzwert meist nicht vollumfänglich als Preis abschöpfen?</b>	Weil Konkurrenten mit teils niedrigeren Preisen das eigene Angebot ansonsten <b>"unverschämt teuer" erscheinen</b> lassen können.	Lektion 3
<b>Was macht die Preisbildung in einem wettbewerbsintensiven Markt komplexer?</b>	Prognosen zu Marktreaktionen auf Preisänderungen lassen sich hier nur <b>sehr schwer einschätzen</b>.	Lektion 4
<b>Warum sind Preiskämpfe für die Anbieter langfristig oft sehr destruktiv?</b>	Weil sie treue Kunden dazu erziehen, preisbewusster zu verhandeln, und langfristig das <b>Preisniveau der gesamten Branche absenken</b>.	Lektion 4
<b>Was versteht man unter einem "Preispremium"?</b>	Das Preispremium ist die <b>Preisdifferenz zum Konkurrenzpreis</b>, die ein Anbieter aufgrund der individuellen Präferenz seiner Kunden am Markt erzielen kann.	Lektion 4
<b>Was passiert mit treuen Kunden während eines Preiskrieges?</b>	Sie erkennen, dass sie die gleiche Leistung günstiger bekommen können, fühlen sich <b>unfair behandelt</b> und entwickeln eine höhere <b>Preissensitivität und Verhandlungsfreude</b>.	Lektion 4
<b>Warum ist die Preispolitik ein so wirkungsvolles Instrument im Marketingmix?</b>	Weil sich Preisänderungen in der Regel <b>unmittelbar und sehr schnell auf den Absatz auswirken</b>.	Lektion 4
<b>Darf ein Unternehmen Preise senken, nur um einen einzelnen Auftrag kurzfristig zu gewinnen?</b>	Nein, ein effektiver Preiswettbewerb erfordert, dass die <b>langfristigen Folgen einer Preispolitik</b> immer gegenüber der kurzfristigen Vorteilhaftigkeit abgewogen werden.	Lektion 4
<b>Aus welchen drei Elementen ergibt sich die Notwendigkeit, den Wettbewerb bei Preisentscheidungen zu berücksichtigen?</b>	Aus der hohen <b>Kreuzpreiselastizität</b>, der starken <b>Reaktionselastizität</b> des Wettbewerbs und der hohen <b>Dynamik</b> im Markt.	Lektion 4
<b>Was versteht man unter "Wettbewerbsinformationen"?</b>	Das sind <b>relevante Erkenntnisobjekte über konkurrierende Unternehmen</b>, insbesondere bezogen auf deren Preisverhalten.	Lektion 4
<b>Welche drei Teilaufgaben sind wesentlich, um Wettbewerbsinformationen zu generieren?</b>	1. <b>Identifikation der relevanten Wettbewerber</b>, 2. <b>Analyse der Preise</b> (historisch, aktuell, zukünftig), 3. <b>Antizipation</b> des möglichen zukünftigen Preisverhaltens.	Lektion 4
<b>Was beinhaltet die Identifikation der relevanten Wettbewerber neben dem direkten Konkurrenten?</b>	Sie umfasst auch die Identifikation des <b>indirekten Wettbewerbs</b>, also von Anbietern mit gleichartigen oder nutzenverwandten Leistungen (z. B. Taxi vs. Bus).	Lektion 4
<b>Warum ist die Analyse der aktuellen Abgabepreise im B2B-Bereich oft schwierig?</b>	Weil offizielle Listenpreise durch vielfältige <b>direkte und nachträglich gewährte Rabatte (Boni)</b> massiv geschmälert werden.	Lektion 4
<b>Was ist ein "Store Check"?</b>	Eine Methode der Informationsbeschaffung im Einzelhandel, bei der die <b>Läden der Mitbewerber direkt aufgesucht werden</b>, um Wettbewerbspreise zu erheben.	Lektion 4
<b>Warum ist bei Preisänderungen die Interpretation ("Signaling") der Konkurrenten oft wichtiger als die Maßnahme selbst?</b>	Weil die Marktreaktion davon abhängt, ob die Konkurrenz eine Preissenkung als <b>offensiven Angriff oder als defensive Verteidigungsmaßnahme</b> wertet.	Lektion 4
<b>Was versteht man unter einem "Preiskrieg"?</b>	Darunter versteht man die <b>Konfrontation mit Konkurrenten</b> im aggressiven Preiswettbewerb.	Lektion 4
<b>Was ist das grundsätzliche Ziel beim "effektiven Preiswettbewerb"?</b>	Es ist wesentlich vorteilhafter, eine <b>Konfrontation im Preiswettbewerb mit Konkurrenten zu vermeiden</b>.	Lektion 4
<b>In welchen drei Ausnahmefällen kann eine aggressive Preispolitik strategisch sinnvoll sein?</b>	1. Bei einem erheblichen <b>Grenzkostenvorteil</b>, 2. bei einem Fokus auf einen <b>sehr kleinen Teilmarkt</b>, 3. wenn das Produkt die <b>Grundlage für Folgegeschäfte</b> bildet.	Lektion 4
<b>Wie lautet die Definition für "Grenzkosten" (Marginalkosten)?</b>	Das sind diejenigen Kosten, die durch die <b>Produktion einer zusätzlichen Mengeneinheit</b> eines Produktes entstehen.	Lektion 4
<b>Was ist mit der strategischen Kostenführerschaft oft verknüpft?</b>	Die Idee der <b>Leistungsvereinfachung</b>, bei der emotionale oder symbolische Leistungsbestandteile vermieden werden.	Lektion 4
<b>Was charakterisiert einen "vollkommenen Markt"?</b>	Er ist gekennzeichnet von <b>vollständiger Transparenz</b>, vollständiger Information aller Teilnehmer und Entscheidungen <b>ohne sachliche oder persönliche Präferenzen</b>.	Lektion 4
<b>Warum wäre eine Preisdifferenzierung auf einem vollkommenen Markt unmöglich?</b>	Weil die vollständig informierten Nachfrager ohne Präferenzen das Produkt immer <b>nur zum günstigsten Preis</b> kaufen würden.	Lektion 4
<b>Von welcher Marktform geht man bei der praktischen Preispolitik in der Realität aus?</b>	In der Realität handelt es sich in aller Regel um <b>unvollkommene Märkte</b>, auf denen unterschiedliche Zahlungsbereitschaften existieren.	Lektion 4
<b>Worauf sollten sich Unternehmen konzentrieren, anstatt Preiskämpfe zu führen?</b>	Auf die Suche und den Ausbau von <b>echten Wettbewerbsvorteilen</b> und die Schaffung von möglichst hohem <b>Nutzen für den Kunden</b>.	Lektion 4
<b>Was versteht man allgemein unter Preispositionierung?</b>	Preispositionierung bezeichnet die Relationen von <b>Preis und Leistung</b> aus Sicht der Kunden auf unterschiedlichen Niveaus.	Lektion 5
<b>Welche fünf idealtypischen Preispositionen gibt es?</b>	<b>Niedrig-, Mittel- und Premiumpreisposition</b> sowie die <b>Vorteils- und Übervorteilsposition</b>.	Lektion 5
<b>Wie ist die Niedrigpreispositionierung definiert?</b>	Aus Kundensicht wird eine im Vergleich zum Marktdurchschnitt <b>geringere Leistung zu einem dauerhaft niedrigen Preis</b> angeboten. Beispiel: ALDI.	Lektion 5
<b>Was definiert die Vorteilsposition?</b>	Sie spiegelt eine <b>besonders hohe Leistung zu einem dauerhaft niedrigen Preis</b> wider — für den Anbieter meist sehr unattraktiv.	Lektion 5
<b>Was versteht man unter der Übervorteilsposition?</b>	Sie beschreibt einen <b>besonders hohen Preis zu dauerhaft niedriger Qualität</b> — der Kunde fühlt sich ausgenutzt (Wucher).	Lektion 5
<b>Wie ist die Mittelpreispositionierung definiert?</b>	Es wird eine im Vergleich zum Markt <b>mittlere Leistung zu einem dauerhaft mittleren Preis</b> angeboten.	Lektion 5
<b>Welches Risiko bringt die Mittelpreispositionierung mit sich?</b>	Die Gefahr, als <b>profillos oder als "fauler Kompromiss"</b> wahrgenommen zu werden, da Angriffe "von oben" und "von unten" erfolgen.	Lektion 5
<b>Was definiert die Premiumpreispositionierung?</b>	Dem Kunden wird eine <b>fühlbar höhere Leistung zu einem dauerhaft höheren Preis</b> angeboten. Qualität, Kompetenz und Alleinstellung stehen im Vordergrund.	Lektion 5
<b>Was ist Preisdifferenzierung (Preisdiskriminierung)?</b>	Das Fordern <b>unterschiedlicher Preise für identische Produkte</b> in verschiedenen Marktsegmenten.	Lektion 5
<b>Was ist das übergeordnete Ziel der Preisdifferenzierung?</b>	Die <b>Abschöpfung unterschiedlicher Zahlungsbereitschaften</b>, um den Gesamtgewinn zu steigern.	Lektion 5
<b>Wie definiert sich nachfragerbezogene Preisdifferenzierung?</b>	Preise werden in <b>Abhängigkeit von persönlichen Eigenschaften</b> der jeweiligen Käufer variiert. Beispiel: Studentenrabatt.	Lektion 5
<b>Was ist zeitliche Preisdifferenzierung?</b>	Unterschiedliche Preise in Abhängigkeit vom <b>Kaufzeitpunkt oder Zeitpunkt der Inanspruchnahme</b>. Beispiel: günstigere Telefontarife nachts.	Lektion 5
<b>Was ist räumliche Preisdifferenzierung?</b>	Es werden je nach <b>räumlicher Lage oder Verkaufsort</b> unterschiedliche Preise für dieselbe Leistung gefordert. Beispiel: Theater-Sitzplatzkategorien.	Lektion 5
<b>Was sind "Rate Fences" bei der Preisdifferenzierung?</b>	Rate Fences sind <b>Bedingungen oder Schranken</b>, die Kunden zwingend erfüllen müssen, um einen bestimmten (günstigeren) Preis zu erhalten.	Lektion 5
<b>Was ist ein "Physical Rate Fence"?</b>	Eine physische Unterscheidung des Angebots, die Preisunterschiede rechtfertigt. Beispiel: <b>Business Class vs. Economy Class</b> im Flugzeug.	Lektion 5
<b>Was ist ein "Non-Physical Rate Fence"?</b>	Preisunterschiede durch abstrakte Bedingungen wie Buchungszeitpunkt. Beispiel: <b>Frühbucherrabatt (Advance Purchase)</b>.	Lektion 5
<b>Was ist Yield Management (auch Revenue Management)?</b>	Eine <b>simultane und dynamische Preis- und Kapazitätssteuerung</b> zur Optimierung der Kapazitätsauslastung.	Lektion 5
<b>In welchen Branchen kommt Yield Management vorrangig zum Einsatz?</b>	Bei <b>kapitalintensiven Dienstleistungen mit fixen Kapazitäten</b>. Beispiel: Airlines, Hotellerie, Luftfracht.	Lektion 5
<b>Welche anbieterseitige Bedingung muss für Yield Management gegeben sein?</b>	Die Kapazität muss fix sein und <b>verfallen, wenn sie nicht genutzt wird</b>.	Lektion 5
<b>Was ist das Hauptziel der Preiskommunikation bei Preissenkungen?</b>	Die Preissenkung soll von den Kunden <b>möglichst stark und positiv wahrgenommen werden</b>.	Lektion 5
<b>Was ist das Hauptziel der Preiskommunikation bei Preiserhöhungen?</b>	Die Preiserhöhung soll <b>möglichst nicht als solche wahrgenommen werden</b> und ohne negative Auswirkungen auf den Absatz bleiben.	Lektion 5
<b>Was ist präferenzverstärkende Werbung als Abfederungsmethode?</b>	Die unvermeidbare Preiserhöhung wird mit <b>qualitätsbetonter Werbung verbunden</b>, um den Nutzen zu betonen und die Preiselastizität zu senken.	Lektion 5
<b>Wie funktioniert die Methode der "Geheimhaltung" bei Preiserhöhungen?</b>	Die Erhöhung wird <b>stillschweigend und ohne aktive Kommunikation</b> vorgenommen, in der Hoffnung, dass sie unbemerkt bleibt. Risiko: Image- und Vertrauensschäden.	Lektion 5
<b>Wie funktioniert die "Verkleinerung der Verpackung" (Shrinkflation)?</b>	Der Preis bleibt optisch gleich, aber die <b>Füllmenge wird reduziert</b>, um bekannte Preisschwellen nicht zu überspringen.	Lektion 5
<b>Wie wirkt proaktiver Reputations- und Vertrauensaufbau auf die Preiskommunikation?</b>	Kunden eines hoch angesehenen Unternehmens <b>unterstellen bei Preiserhöhungen keine negativen Motive</b>, was Absatzrückgänge abschwächt.	Lektion 5
<b>Was besagt das Konsistenzband der Preispositionierung?</b>	Es zeigt, dass <b>wahrgenommener Preis und wahrgenommene Leistung in einem ausgewogenen Verhältnis</b> stehen müssen.	Lektion 5
<b>Welche Eigenschaft hat der Markt, wenn eine Preisdifferenzierung durchgeführt werden kann?</b>	Es muss sich um einen <b>unvollkommenen Markt</b> handeln.	Lektion 5
<b>Welche Kostenüberlegung muss für eine sinnvolle Marktsegmentierung erfüllt sein?</b>	Die <b>zusätzlichen Kosten der Marktsegmentierung</b> müssen durch die neu generierten höheren Gewinne gedeckt sein.	Lektion 5
<b>Welches Ziel hat die Preiskommunikation bei Preissenkungen bezogen auf Elastizität?</b>	Das strategische Ziel ist es, die <b>absolute Preiselastizität der Kunden zu erhöhen</b>.	Lektion 5
<b>Welches Ziel hat die Preiskommunikation bei Preiserhöhungen bezogen auf Elastizität?</b>	Das strategische Ziel ist es, die <b>absolute Preiselastizität der Kunden zu senken</b>.	Lektion 5
<b>Warum ist die Vorteilsposition als dauerhafte Geschäftsstrategie nicht geeignet?</b>	Weil sie <b>für den Anbieter wirtschaftlich meist extrem unattraktiv</b> ist, da wertvolle Margen verschenkt werden.	Lektion 5
<b>Wieso ist die Übervorteilsposition am Markt extrem riskant?</b>	Weil sie aus <b>Kundensicht extrem unattraktiv ist</b> und der Kunde sich abgezockt fühlt.	Lektion 5
<b>Welches Risiko birgt die Geheimhaltung von Preiserhöhungen?</b>	Wenn Kunden das Manöver bemerken, kann es zu schweren <b>Image- und Vertrauensschäden</b> führen.	Lektion 5
<b>Wie nutzen Billigfluglinien das Yield Management operativ?</b>	Sie nutzen ein System mit stetig <b>steigenden Preisen bei näher rückendem Abflugdatum</b>.	Lektion 5
<b>Wie müssen die Kostenstrukturen für funktionierendes Yield Management aussehen?</b>	Die <b>variablen Kosten müssen sehr niedrig</b>, aber die fixen Kosten einer Kapazitätserweiterung extrem hoch sein.	Lektion 5
<b>Welche Wirkung hat eine Preissenkung, die bewusst NICHT werblich unterstützt wird?</b>	Der <b>Absatzzuwachs ist oft nicht signifikant</b>, da die Kunden den Preisvorteil schlichtweg übersehen.	Lektion 5
<b>Warum muss die Preisdifferenzierung für Kunden nachvollziehbar sein?</b>	Um <b>Verärgerungen, Missgunst und Neid zu vermeiden</b>.	Lektion 5
<b>Nenne ein Beispiel für einen Rate Fence bezogen auf die Konsumhäufigkeit!</b>	<b>Platinum-Mitglieder</b> eines Vielfliegerprogramms erhalten exklusive Prioritätspreise und Rabatte.	Lektion 5
<b>Nenne ein Beispiel für einen Rate Fence bezogen auf Gruppenzugehörigkeit!</b>	Spezielle <b>Firmenraten (Corporate Rates) oder Alumni-Rabatte</b> für verifizierte Mitglieder.	Lektion 5
<b>Nenne ein Beispiel für einen Rate Fence bezogen auf den Wohnort des Käufers!</b>	<b>Einheimische (Locals) zahlen niedrigere Eintrittspreise</b> als auswärtige Touristen.	Lektion 5
<b>Was ist ein Rate Fence bezogen auf die Flexibilität des Kaufs?</b>	Ein sehr günstiges Flugticket kann nicht storniert werden (<b>Non-refundable</b>), während ein flexibles Ticket teuer ist.	Lektion 5
<b>Was ist ein Rate Fence bezogen auf die Zeit der Nutzung?</b>	Der günstige Preis ist an einen streng definierten Nutzungszeitraum gebunden. Beispiel: <b>"Early Bird Special"</b> vor 18:00 Uhr.	Lektion 5
<b>Was beschreibt der Produktlebenszyklus (PLZ)?</b>	Er ist die modellhafte Betrachtung einer Leistung von der <b>Innovation bis zur Elimination</b> am Markt.	Lektion 6
<b>Wodurch ist die Marktentwicklung in der Einführungsphase gekennzeichnet?</b>	Sie ist durch die <b>Neuartigkeit des Produktes (Innovation)</b> gekennzeichnet, das auf neue Bedürfnisse der Kunden reagiert.	Lektion 6
<b>Wie reagieren Kunden in der Einführungsphase preislich?</b>	Die Kunden honorieren dies mit einer <b>geringen Preissensitivität</b> — sie sind eher preisunempfindlich.	Lektion 6
<b>Worin besteht die primäre Preisstrategie beim Innovationspreis?</b>	Kunden über Vorzüge informieren, <b>Zahlungsbereitschaft voll abschöpfen</b> und bewusst auf Rabatte verzichten.	Lektion 6
<b>Wie verlagert sich das Hauptinteresse der Käufer in der Wachstumsphase?</b>	In der Wachstumsphase verlagert sich das Interesse vom Produktnutzen auf die <b>Kosten und Vorzüge alternativer Angebote</b>.	Lektion 6
<b>Was versteht man unter Skaleneffekten in der Wachstumsphase?</b>	<b>Kosteneinsparungen</b>, die durch erhöhte Produktion und Erfahrungszuwachs erreicht werden.	Lektion 6
<b>Wie wirken besondere Preissenkungen in der Wachstumsphase auf die Konkurrenz?</b>	Besondere Preissenkungen wirken in dieser Phase <b>abschreckend auf Konkurrenten</b>.	Lektion 6
<b>Welche Phase nimmt im PLZ bei vielen Produkten den größten Raum ein?</b>	Die <b>Reifephase</b>.	Lektion 6
<b>Warum sind die Preissetzungsmöglichkeiten in der Reifephase oft begrenzt?</b>	Weil Absatzwachstum nur noch <b>zu Lasten von Marktanteilen anderer Anbieter</b> generiert werden kann.	Lektion 6
<b>Wie wird der Gewinn in der Reifephase hauptsächlich generiert?</b>	Der Gewinn wird gemeinhin durch <b>Kostenvorteile</b> abgeschöpft.	Lektion 6
<b>Was versteht man unter "Entflechtung" in der Reifephase?</b>	Produktangebote, die in der Wachstumsphase <b>gebündelt</b> wurden, werden entflechtet und als <b>Einzelprodukte</b> angeboten. Beispiel: Mobiltelefon und Vertrag getrennt.	Lektion 6
<b>Wodurch sind rückläufige Märkte generell gekennzeichnet?</b>	Durch <b>reduzierte Nachfrage</b>, geringere Absätze, geringere Zahlungsbereitschaften und sinkende Preise.	Lektion 6
<b>Welche drei strategischen Optionen empfehlen sich für rückläufige Märkte?</b>	<b>Teilrückzug, Abernten (Harvesting) und Konsolidierung</b>.	Lektion 6
<b>Was kennzeichnet die Strategie des Teilrückzugs?</b>	Die teilweise oder vollständige <b>Aufgabe bestimmter Marktsegmente</b>, um Ressourcen auf verbliebene Segmente zu verteilen.	Lektion 6
<b>Was ist der Kern der Harvesting-Strategie (Abernten)?</b>	Der stufenweise, vollständige <b>Rückzug aus einer gesamten Branche</b>, wobei schwache Teilmärkte zuerst aufgegeben werden und <b>maximale Einnahmen</b> erzielt werden.	Lektion 6
<b>Wozu dient die eigene Wettbewerbsposition beim Harvesting?</b>	Sie dient lediglich als <b>Finanzierungsquelle für gewinnträchtigere Investitionen</b> auf anderen Märkten.	Lektion 6
<b>Was ist das Ziel der Konsolidierungsstrategie?</b>	In einer rückläufigen Branche die <b>eigene Position zu stärken</b> — durch Preissenkung und Produktionsoptimierung sollen <b>Konkurrenten geschwächt und vertrieben</b> werden.	Lektion 6
<b>Welchen Zustand strebt ein Unternehmen nach erfolgreicher Konsolidierung an?</b>	Gestärkt mit <b>guten Gewinnaussichten, hohem Marktanteil und reduzierten Mitbewerbern</b> aus der Marktumwälzung hervorgehen.	Lektion 6
<b>Warum sinken die Preise in der Reifephase tendenziell?</b>	Die Verbindung von <b>hohem Angebot durch konkurrierende Produkte und einer hohen Preissensitivität</b> der Kunden lässt die Preise sinken.	Lektion 6
<b>Welche produktpolitische Maßnahme kann in der Reifephase die Preissensitivität mildern?</b>	Die <b>Erweiterung der Produktlinie</b>.	Lektion 6
<b>Wie unterscheidet sich der strategische Teilrückzug vom bloßen Ausscheiden?</b>	Der Teilrückzug ist eine <b>geplante, bewusste Entscheidung</b> zur Liquidierung von Vermögenswerten, nicht das durch Insolvenz erzwungene Verlassen.	Lektion 6
<b>Welche finanziellen Herausforderungen hat das Unternehmen in der Einführungsphase?</b>	<b>Hohe Produktionskosten und hohe Werbeausgaben</b>, um Kunden vom Produkt zu überzeugen.	Lektion 6
<b>Welchen Effekt hat eine Preissenkung in der Wachstumsphase?</b>	Sie führt zu <b>beschleunigter Akzeptanz</b> und lässt das anbietende Unternehmen von einem schnelleren Marktwachstum profitieren.	Lektion 6
<b>Wodurch wird die Rentabilität in der Reifephase determiniert?</b>	Von einer soliden <b>Wettbewerbsposition</b>, bestenfalls verbunden mit der <b>Kosten- oder Qualitätsführerschaft</b>.	Lektion 6
<b>Ist ein rückläufiger Markt zwangsläufig eine dauerhafte Gesamterscheinung?</b>	Nein, Marktrückgänge können auch <b>partiell</b> auftreten — räumlich beschränkt oder zeitlich (z.B. Speiseeis im Winter).	Lektion 6
<b>Was versteht man unter Marktsegmentierung?</b>	Die <b>Aufsplittung eines Gesamtmarktes in mehrere homogene Teilmärkte</b>.	Lektion 7
<b>Was bedeutet Segmentierung nach Käufern?</b>	Die differenzierte Betrachtung von Kaufinteressenten, bezogen auf <b>persönliche Eigenschaften des Käufers</b> (z.B. Alter, Beruf).	Lektion 7
<b>Nennen Sie ein Beispiel für die Segmentierung nach dem Kriterium "Alter"!</b>	Freizeiteinrichtungen gewähren unterschiedliche Preise für <b>Erwachsene, Kinder und Rentner</b>.	Lektion 7
<b>Was bedeutet Segmentierung nach Kaufort?</b>	Die differenzierte Betrachtung bezogen auf den <b>Ort, an dem der Kaufvorgang abgeschlossen</b> wird.	Lektion 7
<b>Was bedeutet Segmentierung nach Kaufzeitpunkt?</b>	Die differenzierte Betrachtung hinsichtlich des <b>Zeitpunktes, wann der Kaufvorgang abgeschlossen</b> wird.	Lektion 7
<b>Nennen Sie ein Beispiel für zeitliche Preisdifferenzierung an der Tankstelle!</b>	Zu Beginn von Wochenend-, Feiertags- oder Ferienzeiten lassen sich oft <b>erheblich höhere Benzinpreise</b> beobachten als werktags.	Lektion 7
<b>Was sind "periodische Sonderverkaufsaktionen"?</b>	Aktionen (wie ein "Sale"), bei denen die Ware in bestimmten Zeiträumen zu <b>herabgesetzten Preisen</b> angeboten wird.	Lektion 7
<b>Welches Risiko bergen häufige "Sale"-Aktionen?</b>	Das niedrige Preisimage kann als <b>Normalpreis wahrgenommen</b> werden, Umsätze verschieben sich nur in die Aktionszeiträume.	Lektion 7
<b>Was definieren Volumenrabatte?</b>	Volumenrabatte honorieren mengenmäßig <b>hohe Gesamtabnahmen</b> eines Kunden innerhalb eines definierten Zeitraumes (oft ein Jahr).	Lektion 7
<b>Was sind Bestellrabatte?</b>	Bestellrabatte honorieren <b>seltenere, jedoch größere Bestellungen</b> und sollen Kunden zur Änderung ihres Bestellverhaltens ermutigen.	Lektion 7
<b>Worin unterscheiden sich Volumen- und Bestellrabatte?</b>	Volumenrabatte pflegen die <b>Beziehung zu Großabnehmern</b>, Bestellrabatte ermutigen zur <b>Änderung des Bestellverhaltens</b>.	Lektion 7
<b>Was versteht man unter Produktbündelung?</b>	Die Kombination <b>mehrerer Einzelprodukte zu einem Gesamtprodukt</b>, das günstiger als die Summe der Einzelpreise verkauft wird.	Lektion 7
<b>Welchen psychologischen Effekt hat die Produktbündelung auf preissensitive Kunden?</b>	Das Bündel erscheint günstig, sodass diese Kunden in der Summe oft <b>sogar mehr ausgeben, als sie ursprünglich geplant</b> haben.	Lektion 7
<b>Wie verhält sich die Preissensitivität von Großabnehmern im Vergleich zu Kleinabnehmern?</b>	Großabnehmer sind zumeist <b>preissensitiver</b>, da sie einen höheren finanziellen Anreiz haben, sich zu informieren.	Lektion 7
<b>Wie können Volumenrabatte indirekt durch Verpackungsgrößen umgesetzt werden?</b>	Durch <b>Großverpackungen</b>, bei denen der Liter-/Kilopreis geringer ausfällt als bei Kleinpackungen.	Lektion 7
<b>Warum bieten Gastronomen reduzierte Mittagstische an?</b>	Weil die <b>Preissensitivität mittags höher</b>, die generelle <b>Ausgabebereitschaft jedoch niedriger</b> ist als abends.	Lektion 7
<b>Wie kann ein Anbieter bei sperrigen Produkten indirekt nach Raum differenzieren?</b>	Durch die bewusste <b>Übernahme von Transportkosten</b> für weit entfernte Kunden.	Lektion 7
<b>Welches übergeordnete Ziel verfolgt die Marktsegmentierung in der Preispolitik?</b>	Unterschiedliche <b>Preissensitivitäten und Ausgabebereitschaften</b> der Kunden abzuschöpfen.	Lektion 7
<b>Was ist das übergeordnete Ziel des Verkäufers bei Preisverhandlungen?</b>	<b>Werte für das Unternehmen generieren</b> und den Preis als Gegenwert für seine Leistung realisieren.	Lektion 8
<b>Welche drei wesentlichen Käufertypen unterscheidet man?</b>	<b>Preisorientierte, loyale und wertorientierte</b> Käufer.	Lektion 8
<b>Was ist das typische Ziel von preisorientierten Käufern?</b>	Sie streben einen Kauf zu <b>möglichst geringen Kosten</b> an, sofern das Produkt ihre Anforderungen erfüllt.	Lektion 8
<b>Was besagt die Strategie der "selektiven Beteiligung" bei preisorientierten Käufern?</b>	Der Anbieter bewertet die Rentabilität und schließt nur ab, wenn <b>marginale Gewinnbeiträge</b> erzielt werden und rentablere Geschäfte nicht gefährdet sind.	Lektion 8
<b>Warum fällt es Vertriebsmitarbeitern oft schwer, unrentable Großkunden aufzugeben?</b>	Weil Vertriebler oft nach <b>Umsatz oder Absatz</b> und nicht nach Margen entlohnt werden.	Lektion 8
<b>Welches Kriterium ist für loyale Käufer kaufentscheidend?</b>	Eine einheitlich gute <b>Produktqualität</b> sowie ein als <b>vertrauenswürdig</b> wahrgenommener Lieferant zur Risikoreduktion.	Lektion 8
<b>Welche Verhandlungsstrategie empfiehlt sich gegenüber loyalen Kunden?</b>	Die <b>Qualität, Leistungsbereitschaft und Zuverlässigkeit</b> in den Vordergrund stellen und Preisstrukturen aufbauen, die Vergleiche mit Mitbewerbern erschweren.	Lektion 8
<b>Was zeichnet die Ziele eines wertorientierten Käufers aus?</b>	Weder an der bestmöglichen Qualität noch am günstigsten Preis interessiert — sucht das Produkt mit dem <b>größten Nutzen</b>.	Lektion 8
<b>Was versteht man unter der "Subtraktionsmethode"?</b>	Der bewusste <b>Verzicht auf einige im ursprünglichen Angebot enthaltene Leistungen</b>, um einen niedrigeren Preis zu rechtfertigen. Beispiel: Autohaus entfernt Sitzheizung.	Lektion 8
<b>Welchen psychologischen Zweck verfolgt die Subtraktionsmethode?</b>	Die Kunden werden gezwungen, den weggelassenen Produkteigenschaften <b>einen bestimmten Wert beizumessen</b> (nämlich die Preisdifferenz).	Lektion 8
<b>Welche zwei Bereiche haben unternehmensintern oft unterschiedliche Ziele bei Preisentscheidungen?</b>	<b>Marketing/Vertrieb</b> (tendiert zu niedrigeren Preisen) und <b>Finanz-/Rechnungswesen</b> (tendiert zu höheren Preisen).	Lektion 8
<b>Wann sollte die Preisentscheidungskompetenz in der Hierarchie höher angesiedelt sein?</b>	Je <b>bedeutsamer</b> das Produkt, je <b>homogener</b> die Märkte, je <b>kritischer</b> die Preiskoordination und je <b>wichtiger</b> das Signaling an Wettbewerber.	Lektion 8
<b>Welche drei Aspekte muss ein Verkäufer kennen, um erfolgreich zu verhandeln?</b>	Das <b>Kaufverhalten</b> der Käufertypen, deren <b>Preissensitivität</b> und deren individuelle <b>Einkaufsziele</b>.	Lektion 8
<b>Wie sollte die Argumentation bei wertorientierten Käufern gestaltet sein?</b>	Nicht allgemeine Produkteigenschaften hervorheben, sondern dem Kunden seinen spezifischen <b>Nutzenvorteil</b> erläutern.	Lektion 8
<b>Was ist die Konsequenz, wenn mit einem preisorientierten Kunden keine rentable Beziehung möglich ist?</b>	Die Geschäftsbeziehung sollte <b>konsequent aufgegeben</b> werden.	Lektion 8
<b>Welche immateriellen Bestandteile schätzt der loyale Käufer?</b>	<b>Expertise und zuverlässigen Service</b>.	Lektion 8
<b>Worauf fokussiert der Finanzbereich bei Preisentscheidungen?</b>	Auf <b>Margen- und Kostenbetrachtungen</b> — er tendiert eher zu höheren Preisen.	Lektion 8
<b>Welche drei Praktiken der Preispolitik werden als schädlich empfunden?</b>	<b>Preisabsprachen, Preisdiskriminierung und Preismogelei</b>.	Lektion 9
<b>Wie definiert man Preisabsprachen?</b>	Wenn mehrere Anbieter Absprachen über die <b>Höhe ihrer Preise</b> treffen und diese gemeinschaftlich festlegen.	Lektion 9
<b>Was sind die marktwirtschaftlichen Folgen von Preisabsprachen?</b>	Sie <b>hebeln den Wettbewerb aus</b>, wirken leistungshemmend und führen zu <b>überhöhten Preisen</b> für Kunden.	Lektion 9
<b>Sind Preisabsprachen in Deutschland erlaubt?</b>	Nein, sie sind aufgrund des <b>Wettbewerbsrechts gesetzlich verboten</b>.	Lektion 9
<b>Was versteht man unter Preisdiskriminierung?</b>	Wenn der Verkäufer für <b>exakt das gleiche Produkt</b> bei seinen Kunden <b>unterschiedliche Preise</b> verlangt.	Lektion 9
<b>Ist Preisdiskriminierung in Deutschland gesetzlich verboten?</b>	<b>Nein</b>, in Deutschland ist sie nicht verboten und obliegt dem Verhandlungsgeschick.	Lektion 9
<b>Was bedeutet "Preismogelei"?</b>	Der Anbieter gibt Preise oder Preiseinsparungen vor, die <b>tatsächlich gar nicht vorhanden</b> sind.	Lektion 9
<b>Was ist ein "Mondpreis"?</b>	Ein vorheriger, <b>völlig unrealistischer und extra hoher Preis</b>, um augenscheinlich viel Rabatt gewähren zu können.	Lektion 9
<b>Was ist das Ziel von "Kampfpreisen"?</b>	Mit ruinös niedrigen Preisen Konkurrenten <b>verdrängen und eine Wettbewerbsbereinigung</b> vornehmen, um danach die Preise wieder anzuheben.	Lektion 9
<b>Wie finanzieren Anbieter extrem niedrige Kampfpreise oft?</b>	Durch eine <b>Mischkalkulation</b>, bei der Verluste durch Gewinne bei anderen eigenen Produkten ausgeglichen werden.	Lektion 9
<b>Was versteht man unter "Preisbindung"?</b>	Die Möglichkeit von Herstellern, die von ihren Händlern gegenüber Endverbrauchern geforderten <b>Preise fix zu bestimmen</b>.	Lektion 9
<b>Ist die Preisbindung heutzutage ein legales Instrument?</b>	In den meisten Ländern <b>gesetzlich verboten</b>, mit Ausnahmen wie der <b>Buchpreisbindung</b>.	Lektion 9
<b>Welchen Bereich regeln Art. 81 und 82 des EG-Vertrages?</b>	Vereinbarungen, die den <b>Wettbewerb im EU-Handel behindern</b>, und die missbräuchliche Ausnutzung einer <b>marktbeherrschenden Stellung</b>.	Lektion 9
<b>Wofür steht das GWB?</b>	<b>Gesetz gegen Wettbewerbsbeschränkungen</b> (auch Kartellgesetz) — regelt u.a. marktbeherrschende Unternehmen.	Lektion 9
<b>Wofür steht das UWG?</b>	<b>Gesetz gegen unlauteren Wettbewerb</b> — regelt u.a. Bedingungen für Preisnachlässe bei Verkaufsförderungsmaßnahmen.	Lektion 9
<b>Was fordert die PAngV (Preisangabenverordnung)?</b>	Dass <b>Endverbraucherpreise immer einschließlich der Umsatzsteuer</b> (als Bruttopreise) anzugeben sind.	Lektion 9
<b>Mit welchen Instrumenten versuchen Anbieter bei Preisabsprachen das Preisniveau zu kontrollieren?</b>	Oft mit gemeinsam festgelegten <b>Mindestpreisen für Anbieter</b> oder <b>Höchstpreisen für Nachfrager</b>.	Lektion 9
<b>Warum gilt Preisdiskriminierung in vielen Gesellschaftsordnungen als unfair?</b>	Weil es im Verhältnis der Kunden untereinander zu <b>Missgunst und Neid</b> führen kann.	Lektion 9
<b>Welches gesetzliche Instrument schafft Preistransparenz bei Kreditinstituten?</b>	Die Pflicht, neben den Nominalzinssätzen auch <b>effektive Jahreszinsen</b> auszuweisen.	Lektion 9
<b>Dürfen Händler Produkte dauerhaft unter Einstandspreis verkaufen?</b>	In manchen Ländern ist es Anbietern <b>gesetzlich untersagt</b>, Produkte unter Einstandspreis zu verkaufen.	Lektion 9
<b>Wodurch wird jede Marktordnung, abseits von Gesetzen, geprägt?</b>	Durch allgemeine <b>Handelsbräuche und Regeln der Fairness</b>.	Lektion 9
<b>Nenne ein Beispiel für eine legale Ausnahme der Preisbindung!</b>	Die gesetzliche <b>Buchpreisbindung</b>.	Lektion 9
<b>Was passiert, wenn ein Unternehmen fixe Kosten fälschlicherweise in die Preiskalkulation einbezieht?</b>	Es besteht die Gefahr, dass der kalkulierte Preis <b>zu hoch</b> ausfällt, wodurch am Markt nicht genügend Absatz erzielt wird und das Unternehmen Aufträge verliert, die eigentlich <b>positive Deckungsbeiträge</b> geliefert hätten.	Lektion 2
<b>Was passiert mit dem Break-even-Punkt, wenn der Verkaufspreis pro Stück erhöht wird?</b>	Der Break-even-Punkt <b>sinkt</b>, da pro verkauftem Stück ein höherer Deckungsbeitrag erzielt wird und die Fixkosten somit <b>schneller gedeckt</b> werden.	Lektion 2
<b>Wie unterscheidet sich der "Grundnutzen" vom "Zusatznutzen" eines Produktes?</b>	Der <b>Grundnutzen</b> umfasst sachliche und physische Funktionalitäten, während der <b>Zusatznutzen</b> zusätzliche Attribute wie Image, Marke oder begleitende Servicedienstleistungen beinhaltet.	Lektion 3
<b>Was passiert, wenn die Konsumentenrente bei einem Produkt besonders hoch ist?</b>	Es <b>lockt weitere Anbieter in den Markt</b>, da die hohe Zahlungsbereitschaft der Kunden attraktive Gewinnmöglichkeiten verspricht, was langfristig den <b>Wettbewerb intensiviert</b>.	Lektion 3
<b>Warum kann ein Anbieter den wirtschaftlichen Wert eines Produktes nicht immer vollständig abschöpfen?</b>	Weil auf unvollkommenen Märkten die Kunden <b>nicht über vollständige Informationen</b> verfügen und keine vollkommen rationalen Entscheidungen treffen, weshalb die tatsächliche Zahlungsbereitschaft oft unter dem theoretischen Wert liegt.	Lektion 3
<b>Wie lautet die Formel zur Berechnung des wirtschaftlichen Wertes (Tauschwertes) eines Produktes?</b>	$\text{Wirtschaftlicher Wert} = \text{Referenzwert} + \text{Differenzierungswert}$	Lektion 3
<b>Was passiert mit der Preissensitivität eines Kunden, wenn dieser ein Produkt als einzigartig wahrnimmt, es jedoch NICHT als wichtig erachtet?</b>	Der <b>Effekt des einzigartigen Wertes greift nicht</b>, denn die Kunden müssen die Differenzierung nicht nur wahrnehmen, sondern ihr auch einen entsprechenden <b>Wert beimessen</b>.	Lektion 3
<b>Nenne die 9 Effekte, die die Preissensitivität des Kunden beeinflussen!</b>	1. <b>Substituteneffekt</b>, 2. <b>Effekt des einzigartigen Wertes</b>, 3. <b>Wechselkosteneffekt</b>, 4. <b>Effekt des schwierigen Vergleiches</b>, 5. <b>Preis-Qualitäts-Effekt</b>, 6. <b>Ausgabeneffekt</b>, 7. <b>Endnutzeneffekt</b>, 8. <b>Kostenteilungseffekt</b>, 9. <b>Fairness-Effekt</b> (+ Lagerbestandseffekt als 10.).	Lektion 3
<b>Was unterscheidet die Preiselastizität von der Kreuzpreiselastizität inhaltlich?</b>	Die <b>Preiselastizität</b> misst die Absatzreaktion auf Preisänderungen des <b>eigenen</b> Produktes, die <b>Kreuzpreiselastizität</b> misst die Absatzreaktion des eigenen Produktes auf Preisänderungen eines <b>Konkurrenzproduktes</b>.	Lektion 3
<b>Was bedeutet eine Preiselastizität von E = -0,5?</b>	Die Nachfrage reagiert <b>unelastisch</b>: Eine Preiserhöhung von 10 % führt nur zu einem Absatzrückgang von <b>5 %</b>. Die prozentuale Mengenänderung ist kleiner als die prozentuale Preisänderung.	Lektion 3
<b>Welche Preiselastizitätswerte kennzeichnen eine elastische vs. unelastische Nachfrage?</b>	Bei $|E| > 1$ ist die Nachfrage <b>elastisch</b> (starke Reaktion), bei $|E| < 1$ <b>unelastisch</b> (schwache Reaktion) und bei $|E| = 1$ <b>einheitselastisch</b>.	Lektion 3
<b>Warum treffen Kunden laut Skript meist keine vollkommen rationalen Kaufentscheidungen?</b>	Weil sie auf unvollkommenen Märkten <b>keine vollständigen Marktinformationen</b> besitzen und ihre Entscheidungen von <b>subjektiven Faktoren</b> wie Emotionen, Bequemlichkeit oder Gewohnheit beeinflusst werden.	Lektion 3
<b>Welche verkäuferische Herausforderung ergibt sich aus dem Konzept des Nutzwertes?</b>	Der Verkäufer muss den <b>Nutzwert des Kunden möglichst genau einschätzen</b>, da sonst die Gefahr besteht, dass Preishöhe und empfundener Nutzen nicht übereinstimmen und das Geschäft nicht zustande kommt.	Lektion 3
<b>Welche Rolle spielt die Preis-Absatz-Funktion im Vergleich zur reinen Kostenbetrachtung?</b>	Die Preis-Absatz-Funktion zeigt den Zusammenhang zwischen Preis und Nachfragemenge am Markt und ist <b>schwieriger zu ermitteln</b>, da sie auch <b>externe Marktfaktoren</b> berücksichtigt, während Kostenbetrachtungen auf <b>internen Daten</b> basieren.	Lektion 3
<b>Was passiert, wenn ein Produkt auf dem Markt als "unverschämt teuer" wahrgenommen wird?</b>	Der <b>Fairness-Effekt</b> setzt ein: Die Kunden reagieren stark preissensitiv, empfinden den Preis als unverhältnismäßig und <b>kaufen das Produkt möglicherweise nicht</b>, selbst wenn der objektive Nutzen hoch ist.	Lektion 3
<b>Wie verändert sich das Kaufverhalten eines Kunden, wenn die Wechselkosten zu einem Alternativanbieter sehr hoch sind?</b>	Der Kunde bleibt eher beim aktuellen Anbieter und ist <b>weniger preissensitiv</b>, da der Aufwand des Wechsels (monetär und nicht monetär) die mögliche Ersparnis übersteigt.	Lektion 3
<b>Welchen Einfluss hat die Preiselastizität auf die Deckungsbeitragsrechnung?</b>	Eine hohe Preiselastizität bedeutet, dass Preisänderungen <b>starke Absatzveränderungen</b> auslösen, wodurch sich der <b>Gesamtdeckungsbeitrag</b> trotz höherem Stückdeckungsbeitrag verschlechtern kann.	Lektion 3
<b>Was passiert mit dem Referenzwert, wenn ein neuer Billiganbieter in den Markt eintritt?</b>	Der Referenzwert <b>sinkt</b>, da die preislich billigste Alternative am Markt jetzt günstiger ist, wodurch alle anderen Anbieter einen <b>höheren Differenzierungswert</b> nachweisen müssen, um ihren Preis zu rechtfertigen.	Lektion 3
<b>Warum führen kurzfristige Preisaktionen langfristig oft zu negativen Folgen für alle Anbieter?</b>	Weil sie Kunden zu höherer <b>Preissensitivität und Verhandlungsfreude erziehen</b>, das gesamte <b>Preisniveau der Branche absenken</b> und Preiskämpfe auslösen, die für alle Beteiligten destruktiv sind.	Lektion 4
<b>Was versteht man unter "direktem" vs. "indirektem" Wettbewerb bei der Identifikation relevanter Wettbewerber?</b>	<b>Direkter Wettbewerb</b> umfasst Anbieter identischer Leistungen, <b>indirekter Wettbewerb</b> umfasst Anbieter gleichartiger oder <b>nutzenverwandter Leistungen</b> (z. B. Taxi vs. Bus vs. Buslinie).	Lektion 4
<b>Warum kann die Interpretation einer Preissenkung durch die Konkurrenz entscheidend sein?</b>	Weil die Wettbewerber eine Preissenkung entweder als <b>offensiven Angriff</b> zur Marktanteilseroberung oder als <b>defensive Verteidigungsmaßnahme</b> deuten können, was zu völlig unterschiedlichen Reaktionen führt.	Lektion 4
<b>Welche Voraussetzung muss ein Unternehmen erfüllen, um langfristig eine Niedrigpreisstrategie erfolgreich zu betreiben?</b>	Es muss über <b>dauerhafte Kostenvorteile</b> verfügen, etwa durch Skaleneffekte, effiziente Prozesse und Leistungsvereinfachung, um auch bei niedrigen Preisen <b>ausreichende Renditen</b> zu erwirtschaften.	Lektion 4
<b>Warum ergibt sich aus der hohen Kreuzpreiselastizität die Notwendigkeit, den Wettbewerb ständig zu beobachten?</b>	Weil bei hoher Kreuzpreiselastizität Preisänderungen der Konkurrenz <b>unmittelbar den eigenen Absatz</b> beeinflussen und das Unternehmen schnell reagieren muss.	Lektion 4
<b>Was unterscheidet die "Reaktionselastizität" von der "Kreuzpreiselastizität"?</b>	Die <b>Kreuzpreiselastizität</b> misst die Wirkung von Konkurrenzpreisänderungen auf den <b>eigenen Absatz</b>, während die <b>Reaktionselastizität</b> beschreibt, wie stark der <b>Wettbewerber selbst</b> auf eigene Preisänderungen reagiert.	Lektion 4
<b>Was ist die strategische Empfehlung als Alternative zu Preiskämpfen?</b>	Sich auf den <b>Grundgedanken des Marketings</b> zu konzentrieren: die Suche und den Ausbau von <b>echten Wettbewerbsvorteilen</b> sowie die Schaffung von möglichst hohem <b>Nutzen für den Kunden</b>.	Lektion 4
<b>Warum ist das Einkoppeln der eigenen Preise an die Wettbewerbspreise langfristig keine gute Strategie?</b>	Weil es die Preisvergleiche der Kunden zwar abfedert, aber gleichzeitig den Raum für <b>eigene Preispremien</b> verringert und das Durchschnittspreispolitik dem Abschöpfen der eigenen <b>Differenzierungsvorteile</b> entgegensteht.	Lektion 4
<b>Welche Quellen können zur Beschaffung von Wettbewerbspreisinformationen genutzt werden?</b>	Etwa die eigene <b>Außendienst- und Vertriebsmannschaft</b>, <b>Kunden</b>, oder im Einzelhandel das direkte <b>Aufsuchen der Mitbewerberläden</b> (Store Check).	Lektion 4
<b>Was passiert, wenn Preissenkungen eher zu Marktanteilen als zum Gewinn führen?</b>	Absatz alleine hat <b>keine Aussage auf den Gewinn</b>. Die Steigerung der Marktanteile zeigt sich tendenziell eher bei <b>Erhöhung von Preisen</b>, nicht bei deren Senkung.	Lektion 4
<b>Warum beginnen Preiskämpfe üblicherweise mit vermehrten Preiszugeständnissen?</b>	Weil Unternehmen zunächst versuchen, durch <b>selektive Rabatte und Sonderkonditionen</b> ihren Absatz zu steigern, was die konkurrierenden Anbieter dann als neues Preisniveau erkennen und <b>nachziehen</b>.	Lektion 4
<b>Was versteht man unter "Signaling" im Kontext der wettbewerbsgesteuerten Preispolitik?</b>	Die <b>bewusste oder unbewusste Kommunikation von Preisintentionen</b> an Wettbewerber, wobei die Konkurrenten die Bedeutung der Maßnahme oft für wichtiger halten als die Maßnahme selbst.	Lektion 4
<b>In welcher Situation kann ein Unternehmen einen Preiskrieg bewusst führen, weil das Produkt die Grundlage für Folgegeschäfte bildet?</b>	Wenn ein Produkt als <b>Plattform für spätere aufbauende Produkte</b> dient. Beispiel: <b>Microsoft Windows</b> als günstiges Betriebssystem, das die Grundlage für den Verkauf weiterer Software bildet.	Lektion 4
<b>Was versteht man unter der "Kostenführerschaft" im Kontext der Niedrigpreispositionierung?</b>	Die Fähigkeit eines Unternehmens, durch <b>Leistungsvereinfachung und minimale Kosten</b> entlang der gesamten Wertschöpfungskette den niedrigsten Preis am Markt bieten zu können und dabei trotzdem profitabel zu arbeiten.	Lektion 5
<b>Was bildet bei der Niedrigpreispositionierung die "Unique Selling Proposition" (USP)?</b>	Der <b>niedrige Preis selbst</b> ist das einzigartige Verkaufsargument und der zentrale Wettbewerbsvorteil.	Lektion 5
<b>Warum verträgt sich der Aufbau starker Produktmarken nicht mit der Kostenführerschaft?</b>	Weil <b>Markenaufbau erhebliche finanzielle Investitionen</b> erfordert, die letztlich durch das Produkt getragen werden müssen und den Erklärungsbedarf der Produkte möglichst <b>gering</b> halten sollte.	Lektion 5
<b>Nenne vier Chancen der Premiumpreispositionierung!</b>	1. Vergleichsweise <b>niedrige Preiselastizitäten</b>, 2. <b>Hohe Margen</b> realisierbar, 3. Mehr <b>Leistungsdifferenzierungsmöglichkeiten</b>, 4. Preis ist <b>kein Kampfinstrument</b> (geringere Häufigkeit von Preiskriegen).	Lektion 5
<b>Nenne drei Risiken der Premiumpreispositionierung!</b>	1. <b>Umsatzeinbußen bei sinkendem Wohlstand</b>, 2. Manager müssen der <b>"Versuchung der großen Menge" widerstehen</b>, 3. <b>Kannibalisierungsgefahr</b> durch Produktpiraterie.	Lektion 5
<b>Welche fünf Bedingungen müssen erfüllt sein, damit Preisdifferenzierung funktioniert?</b>	1. <b>Unvollkommener Markt</b>, 2. Identifizierbare <b>Nachfragergruppen mit unterschiedlicher Preisempfindlichkeit</b>, 3. Verschiedene <b>Preiselastizitäten</b> innerhalb der Segmente, 4. <b>Zusätzliche Kosten</b> gedeckt, 5. Für Kunden <b>nachvollziehbar</b>.	Lektion 5
<b>Welche drei Arten der Preisdifferenzierung gibt es?</b>	<b>Nachfragerbezogene</b> (nach Käufereigenschaften), <b>räumliche</b> (nach Verkaufsort) und <b>zeitliche</b> (nach Kauf-/Nutzungszeitpunkt) Preisdifferenzierung.	Lektion 5
<b>Was unterscheidet "Physical Rate Fences" von "Non-Physical Rate Fences"?</b>	<b>Physical Rate Fences</b> basieren auf einer physischen Unterscheidung des Angebots (z. B. Sitzklasse), während <b>Non-Physical Rate Fences</b> auf abstrakten Bedingungen wie <b>Buchungszeitpunkt oder Stornierbarkeit</b> beruhen.	Lektion 5
<b>Welche drei anbieterseitigen Voraussetzungen müssen für Yield Management gegeben sein?</b>	1. Die <b>Kapazität muss fix</b> sein, 2. Die <b>variablen Kosten müssen niedrig</b> und die fixen Kosten einer Kapazitätserweiterung hoch sein, 3. Die Kapazität <b>verfällt, wenn sie nicht genutzt wird</b>.	Lektion 5
<b>Was ist der Unterschied zwischen Yield Management und "normaler" Preisdifferenzierung?</b>	Yield Management ist eine spezielle Abwandlung der <b>zeitlichen Preisdifferenzierung</b>, die <b>simultan und dynamisch</b> Preis und Kapazität steuert, während klassische Preisdifferenzierung eher <b>statische</b> Preisunterschiede nach festen Kriterien setzt.	Lektion 5
<b>Was passiert, wenn eine Preiserhöhung NICHT mit Werbung begleitet wird?</b>	Die Preiserhöhung wirkt sich <b>signifikant negativ</b> auf den Absatz aus, da die Kunden den höheren Preis ohne qualitätsbetonte Argumentation als reine Verteuerung wahrnehmen.	Lektion 5
<b>Was passiert, wenn eine Preissenkung MIT begleitender Werbung kommuniziert wird?</b>	Es kommt zu einem <b>starken Absatzzuwachs</b>, da die Kunden den Preisvorteil wahrnehmen und die preisliche Vorteilhaftigkeit herausgestellt wird.	Lektion 5
<b>Was ist Shrinkflation und warum wird sie eingesetzt?</b>	<b>Shrinkflation</b> bedeutet, dass der Preis optisch gleich bleibt, aber die <b>Füllmenge reduziert</b> wird. Sie wird eingesetzt, um bekannte <b>Preisschwellen nicht zu überspringen</b> und die Preiserhöhung vor dem Kunden zu verschleiern.	Lektion 5
<b>Welche Produkte eignen sich besonders für eine Verkleinerung der Verpackung (Shrinkflation)?</b>	Produkte, die <b>mengenmäßig gut teilbar</b> sind und eine geringe Standardisierung in den Packungsgrößen aufweisen, etwa <b>Fruchtsäfte oder Süßwaren</b>.	Lektion 5
<b>Welche Gefahr besteht beim missbräuchlichen Einsatz von Reputations- und Vertrauensaufbau?</b>	Wenn guter Ruf <b>ausgenutzt</b> wird, um übermäßige Preiserhöhungen durchzusetzen, kann dies langfristig das <b>Vertrauen der Kunden zerstören</b>.	Lektion 5
<b>Nenne ein Beispiel für eine Konsumhäufigkeit als Rate Fence im Tourismus!</b>	<b>Vielflieger-Programme</b>: Platinum-Mitglieder erhalten exklusive Prioritätspreise und Rabatte, die Gelegenheitsfliegern nicht zugänglich sind.	Lektion 5
<b>Was ist der Zusammenhang zwischen Preispositionierung und dem Konsistenzband?</b>	Das Konsistenzband zeigt, dass <b>wahrgenommener Preis und wahrgenommene Leistung in einem ausgewogenen Verhältnis</b> stehen müssen. Positionen außerhalb des Bandes (Vorteils- und Übervorteilsposition) sind langfristig nicht tragbar.	Lektion 5
<b>Warum ist die Preiselastizität eine wichtige Voraussetzung für die Preisdifferenzierung?</b>	Weil die Preiselastizität <b>ausreichend niedrig</b> sein muss, damit Preisänderungen die Höhe der Nachfrage nur in begrenztem Maße beeinflussen und die Segmente <b>trennbar</b> bleiben.	Lektion 5
<b>Was sind die Chancen und Risiken der Mittelpreispositionierung?</b>	<b>Chancen:</b> Bekannt, positiv aufgeladen, helfen Suchkosten zu minimieren. <b>Risiken:</b> Gefahr als <b>"fauler Kompromiss"</b> profillos wahrgenommen zu werden; Angriffe <b>"von oben" und "von unten"</b>; Gefahr der imagemäßigen Überalterung.	Lektion 5
<b>Warum bildet die Kundensicht bei der Preisdifferenzierung den entscheidenden Maßstab?</b>	Weil Produkte nicht nur <b>rein identisch</b> sein müssen, sondern auch Produkte betroffen sind, die lediglich aus <b>Kundensicht identisch</b> erscheinen, obwohl objektive Unterschiede bestehen können.	Lektion 5
<b>Was versteht man unter "Consumption Characteristics" als Rate Fence?</b>	Preisunterschiede basierend auf dem <b>Nutzungszeitpunkt, der Nutzungsdauer oder dem Nutzungsort</b>. Beispiel: "Early Bird Special" vor 18 Uhr im Restaurant oder Mindestaufenthaltsdauer im Hotel.	Lektion 5
<b>Was versteht man unter "Transaction Characteristics" als Rate Fence?</b>	Preisunterschiede basierend auf dem <b>Buchungszeitpunkt, Buchungsort oder der Flexibilität</b> des Tickets. Beispiel: Frühbucher-Rabatte oder Non-refundable Tickets.	Lektion 5
<b>Was ist der zentrale Unterschied zwischen Preiserhöhung MIT und OHNE werbliche Begleitung?</b>	<b>Ohne</b> Werbung hat die Erhöhung eine <b>signifikant negative Wirkung</b> auf den Absatz. <b>Mit</b> qualitätsbetonter Werbung geht der Absatz dagegen <b>nicht fühlbar zurück</b>, da die Kunden den Mehrwert erkennen.	Lektion 5
<b>Was sind die vier klassischen Phasen des Produktlebenszyklus?</b>	<b>Einführungsphase (Innovation), Wachstumsphase, Reifephase und Degenerationsphase</b> (rückläufiger Markt).	Lektion 6
<b>Warum genießt ein innovatives Produkt in der Einführungsphase einen Alleinstellungscharakter?</b>	Weil <b>Wettbewerber in diesem Stadium noch wenig vorhanden</b> sind und das Produkt auf <b>neue Bedürfnisse</b> der Kunden reagiert, die bisher nicht befriedigt wurden.	Lektion 6
<b>Warum stellen vorhandene Wettbewerber in der Einführungsphase keine große Gefahr dar?</b>	Da jeweils <b>ausreichende Gewinne erzielt</b> werden können, wird der Aufwand für <b>Konkurrenzkämpfe gemeinhin vermieden</b>.	Lektion 6
<b>Welche Rolle spielen Skaleneffekte in der Wachstumsphase für die Preisstrategie?</b>	Durch erhöhte Produktion werden <b>Kosten pro Stück gesenkt</b>, was es dem Unternehmen ermöglicht, Preissenkungen durchzuführen und gleichzeitig das <b>Gewinnniveau zu halten</b>.	Lektion 6
<b>Warum können Preissenkungen in der Wachstumsphase abschreckend auf Konkurrenten wirken?</b>	Weil sie signalisieren, dass der Marktführer bereit ist, auf Marge zu verzichten, um <b>Marktanteile zu sichern</b>, was potenzielle Wettbewerber vor dem <b>Risiko eines Markteintritts</b> abschreckt.	Lektion 6
<b>Was passiert mit der Preissensitivität der Kunden beim Übergang von der Wachstums- zur Reifephase?</b>	Die Preissensitivität <b>steigt deutlich an</b>, da sich Kunden nicht mehr unsicher bezüglich des Produktwertes sind und aus einer <b>Vielzahl ähnlicher Güter</b> auswählen können.	Lektion 6
<b>Was versteht man unter "Entflechtung" von Produktbündeln in der Reifephase?</b>	In der Wachstumsphase gebündelt angebotene Produkte werden in der Reifephase wieder als <b>Einzelprodukte getrennt</b> angeboten. Beispiel: <b>Mobiltelefon und Vertrag</b> werden separat verkauft.	Lektion 6
<b>Wie unterscheidet sich der Teilrückzug vom Harvesting?</b>	Beim <b>Teilrückzug</b> werden nur bestimmte Marktsegmente aufgegeben und Ressourcen auf verbliebene Segmente verteilt, beim <b>Harvesting</b> erfolgt ein stufenweiser, <b>vollständiger Rückzug aus der gesamten Branche</b>.	Lektion 6
<b>Warum werden beim Harvesting keine mittel- und langfristigen Investitionen mehr getätigt?</b>	Weil die eigene Wettbewerbsposition nur noch als <b>Finanzierungsquelle</b> dient, um die erzielten Einnahmen in <b>gewinnträchtigere Investitionen auf anderen Märkten</b> umzuleiten.	Lektion 6
<b>Welche finanzielle Voraussetzung ist für eine erfolgreiche Konsolidierungsstrategie nötig?</b>	Das Unternehmen muss über eine <b>hinreichende Finanzlage</b> verfügen, um Schwächen am Markt <b>besser standhalten zu können als alle Mitbewerber</b>.	Lektion 6
<b>Was passiert, wenn ein Unternehmen eine Konsolidierungsstrategie erfolgreich umsetzt?</b>	Es geht gestärkt mit <b>guten Gewinnaussichten, hohem Marktanteil und reduzierten Mitbewerbern</b> aus der Marktumwälzung hervor.	Lektion 6
<b>Warum ist die Erweiterung der Produktlinie eine geeignete Maßnahme in der Reifephase?</b>	Weil sie hilft, die vorherrschende hohe <b>Preissensitivität der Kunden zu mildern</b>, indem differenziertere Angebote die Vergleichbarkeit mit Konkurrenzprodukten erschweren.	Lektion 6
<b>Wie unterscheiden sich die Preisstrategie in der Einführungsphase und in der Reifephase?</b>	In der <b>Einführungsphase</b> geht es um <b>Abschöpfung der Zahlungsbereitschaft</b> bei geringer Preissensitivität; in der <b>Reifephase</b> wird der Gewinn hauptsächlich durch <b>Kostenvorteile</b> bei hoher Preissensitivität generiert.	Lektion 6
<b>Nenne ein Beispiel für ein Produkt, das sich seit Langem in der Reifephase befindet!</b>	<b>Coca-Cola oder Kinderschokolade</b> — diese Produkte haben sich seit vielen Jahren am Markt etabliert und halten sich nahezu unverändert.	Lektion 6
<b>Warum kann der Teilrückzug die Rentabilität eines Unternehmens sogar stärken?</b>	Weil <b>unrentable Märkte aufgegeben</b> werden und die frei gewordenen Ressourcen auf die <b>verbliebenen, rentablen Segmente</b> verteilt werden können, was zu steigenden Marktanteilen in diesen Segmenten führt.	Lektion 6
<b>Warum sind Coupons ein Instrument zur Selbstselektion preissensitiver Kunden?</b>	Preissensitive Kunden nehmen sich die Zeit, <b>Coupons auszuschneiden und einzulösen</b>, während weniger preissensitive Kunden dies nicht tun, sodass der Anbieter bei letzteren <b>mehr Wert abschöpft</b>.	Lektion 7
<b>Wie funktioniert die "Segmentierung nach Produkten"?</b>	Produkte werden in unterschiedlichen <b>Qualitäts- oder Ausstattungsvarianten</b> zu verschiedenen Preisen angeboten, um unterschiedliche Kundensegmente mit unterschiedlicher Zahlungsbereitschaft anzusprechen.	Lektion 7
<b>Wie können Handelsketten die räumliche Segmentierung praktisch umsetzen?</b>	Sie klassifizieren ihre Läden nach <b>Kundschaft, Wettbewerbsintensität oder Ertragsniveau</b> und bepreisen regional unterschiedlich, auch international je nach Einkommensstärke und Entwicklungsstand.	Lektion 7
<b>Was ist der Unterschied zwischen Volumenrabatten und Produktbündelung?</b>	<b>Volumenrabatte</b> honorieren mengenmäßig hohe Abnahmen <b>desselben Produktes</b>, <b>Produktbündelung</b> kombiniert <b>verschiedene Einzelprodukte</b> zu einem günstigeren Gesamtpaket.	Lektion 7
<b>Warum bieten Restaurants Mittagsmenüs günstiger an als Abendessen?</b>	Weil die <b>Preissensitivität mittags höher</b> ist (Wettbewerb mit Bäcker, Schnellimbiss), die <b>Ausgabebereitschaft niedriger</b> und die begrenzte <b>Mittagspause ein eingeschränktes Menüangebot</b> erfordert.	Lektion 7
<b>Was passiert, wenn ein Unternehmen häufig "Sale"-Aktionen durchführt?</b>	Kunden gewöhnen sich daran und <b>warten auf die nächste Aktion</b>, das niedrige Preisimage wird als <b>Normalpreis wahrgenommen</b> und die Umsätze verschieben sich lediglich in die Aktionszeiträume.	Lektion 7
<b>Wie können Unternehmen durch Verpackungsgrößen indirekt Volumenrabatte umsetzen?</b>	Durch <b>Großverpackungen</b>, bei denen der Preis pro Liter oder Kilogramm <b>geringer</b> ausfällt als bei Kleinpackungen, obwohl der absolute Preis höher ist.	Lektion 7
<b>Wie funktioniert die indirekte räumliche Preisdifferenzierung bei sperrigen Produkten?</b>	Der Anbieter übernimmt bewusst die <b>hohen Transportkosten</b> für weit entfernte Kunden, gewährt dadurch indirekt einen <b>höheren Rabatt</b> und entspricht so der <b>erhöhten Preissensitivität</b> dieser Kunden.	Lektion 7
<b>Wie können Bestellrabatte konkret gestaffelt aussehen?</b>	Z. B. <b>3 % Rabatt für 10-20 Kartons</b>, <b>5 % für 20-50 Kartons</b> und <b>10 % für Bestellungen über 50 Kartons</b>.	Lektion 7
<b>Nenne ein Beispiel für Produktbündelung in der Gastronomie!</b>	Ein Restaurant bietet <b>Einzelgerichte</b> an, die aber auch als <b>Menü zu einem niedrigeren Komplettpreis</b> bestellt werden können.	Lektion 7
<b>Warum geben preissensitive Kunden bei Produktbündeln oft mehr aus als geplant?</b>	Weil das Bündel im Vergleich zu den Einzelpreisen <b>als günstig erscheint</b>, wodurch Kunden Produkte mitkaufen, die sie einzeln <b>nicht erworben hätten</b>.	Lektion 7
<b>Warum werden in der Wachstumsphase Produkte häufig im Bündel angeboten?</b>	Um Kunden einen <b>möglichst hohen Gesamtnutzen</b> zu bieten (z. B. iPad mit Mobilfunktarif) und dadurch die <b>Marktdurchdringung zu beschleunigen</b>.	Lektion 7
<b>Was ist der Vorteil von Gutscheinen und Coupons für die Segmentierung?</b>	Sie ermöglichen eine <b>Selbstselektion</b>: Preissensitive Kunden lösen den Coupon ein und erhalten einen Rabatt, weniger preissensitive Kunden ignorieren ihn, wodurch bei letzteren <b>mehr Wert abgeschöpft</b> wird.	Lektion 7
<b>Wie nutzen Hersteller von Konsumgütern Etiketten mit Rückerstattungsangeboten zur Segmentierung?</b>	Besonders <b>preissensitive Neukunden</b> werden durch den niedrigen effektiven Preis akquiriert, während weniger preissensitive Kunden das Produkt <b>probieren, den Coupon aber nicht einlösen</b> — bei ihnen wird so mehr Wert abgeschöpft.	Lektion 7
<b>Wie können Hotels die Segmentierung nach Kaufort praktisch umsetzen?</b>	Sie bieten denselben Zimmertyp zu <b>unterschiedlichen Preisen</b> je nach Buchungskanal an — z. B. günstiger über die <b>eigene Website</b> als über ein <b>Reisebüro oder Buchungsportal</b>.	Lektion 7
<b>Was versteht man unter "Segmentierung nach Produkten" im Kontext der Marktsegmentierung?</b>	Die Gestaltung <b>verschiedener Produktvarianten</b> (z. B. unterschiedliche Ausstattungsniveaus oder Qualitätsstufen) für unterschiedliche Kundensegmente, um verschiedene <b>Zahlungsbereitschaften</b> abzudecken.	Lektion 7
<b>Welche Wettbewerbssituation herrscht mittags für Restaurants im Vergleich zum Abend?</b>	Mittags konkurrieren Restaurants nicht nur untereinander, sondern auch mit <b>Bäckern, Lebensmittelgeschäften und Schnellimbissen</b>, was zu einer gänzlich anderen und <b>intensiveren Wettbewerbssituation</b> führt.	Lektion 7
<b>Was versteht man bei Preisverhandlungen unter der "selektiven Beteiligung" am Einkaufsvolumen?</b>	Der Anbieter bewertet die <b>kurzfristige Rentabilität und langfristigen Folgen</b> jeder Transaktion und tätigt Verkaufsabschlüsse nur dann, wenn <b>marginale Gewinnbeiträge</b> erzielt werden und <b>rentablere Geschäfte nicht gefährdet</b> werden.	Lektion 8
<b>Warum ist es für loyale Kunden wichtiger, einen vertrauenswürdigen Lieferanten zu haben als den günstigsten Preis?</b>	Weil der vertrauenswürdige Lieferant dem Kunden eine <b>Risikoreduktion</b> bietet und die einheitlich gute <b>Produktqualität und Zuverlässigkeit</b> den Preis als <b>nachrangiges Kaufkriterium</b> erscheinen lässt.	Lektion 8
<b>Warum empfiehlt es sich, bei loyalen Kunden Preisstrukturen aufzubauen, die den Vergleich mit Mitbewerbern erschweren?</b>	Weil dadurch <b>Alternativsuche und Abwanderungsgedanken</b> des Kunden frühzeitig ausgehebelt werden und der Kunde weniger leicht nachprüfen kann, ob ein Konkurrenzangebot tatsächlich günstiger ist.	Lektion 8
<b>Was ist der Hauptunterschied zwischen der Argumentation bei wertorientierten und bei preisorientierten Käufern?</b>	Bei <b>wertorientierten</b> Käufern steht der <b>individuelle Nutzenvorteil</b> im Vordergrund, bei <b>preisorientierten</b> Käufern ist die Argumentation über Nutzen schwierig, da der <b>Preis das dominierende Kaufkriterium</b> ist.	Lektion 8
<b>Warum tendiert der Finanzbereich zu höheren Preisen, während Marketing/Vertrieb zu niedrigeren tendiert?</b>	Der <b>Finanzbereich</b> fokussiert auf <b>Margen- und Kostenbetrachtungen</b> und will Rentabilität sichern, während <b>Marketing/Vertrieb</b> eher den <b>Absatz steigern</b> und Kunden gewinnen will — oft auf Kosten der Marge.	Lektion 8
<b>Warum sollten Vertriebsmitarbeiter nicht ausschließlich nach Umsatz oder Absatz entlohnt werden?</b>	Weil sie dann dazu neigen, unrentable Großkunden zu halten und <b>unprofitable Geschäftsbeziehungen</b> nicht aufzugeben, da ein Umsatzrückgang sich <b>negativ auf ihre persönliche Entlohnung</b> auswirkt.	Lektion 8
<b>Was passiert, wenn ein Vertriebler bei einem wertorientierten Käufer nur allgemeine Produkteigenschaften hervorhebt?</b>	Er geht <b>am Wesentlichen vorbei</b>, da wertorientierte Käufer nicht allgemeine Qualität, sondern den <b>spezifischen Nutzenvorteil</b> für ihre individuelle Situation verstehen wollen.	Lektion 8
<b>Nenne die sechs Kriterien, nach denen die Preisentscheidungskompetenz höher in der Hierarchie angesiedelt sein sollte!</b>	Je <b>bedeutsamer</b> das Produkt, je besser <b>Topmanager informiert</b> sind, je <b>homogener</b> die Märkte, je <b>kritischer</b> die Preiskoordination, je weniger die <b>Kultur auf Gesamtziele fokussiert</b> ist, je wichtiger das <b>Signaling</b> an Wettbewerber.	Lektion 8
<b>Wie unterscheidet sich die Preismogelei von der Preisdiskriminierung?</b>	Bei <b>Preismogelei</b> gibt der Anbieter Preise oder Einsparungen vor, die <b>tatsächlich nicht vorhanden</b> sind (Täuschung), während bei <b>Preisdiskriminierung</b> tatsächlich <b>unterschiedliche Preise</b> für dasselbe Produkt verlangt werden.	Lektion 9
<b>Welche konkreten Instrumente setzen Kartelle bei Preisabsprachen ein?</b>	Sie arbeiten mit gemeinsam festgelegten <b>Mindestpreisen für Anbieter</b> oder <b>Höchstpreisen für Nachfrager</b>, um das <b>Preisniveau künstlich</b> zu kontrollieren.	Lektion 9
<b>Warum greift der Gesetzgeber bei Preismogelei ein?</b>	Um <b>Preistransparenz</b> für den Kunden zu schaffen und ihn vor <b>Tricks und irreführenden Preisangaben</b> zu schützen, die zum Kauf animieren sollen.	Lektion 9`;
